meta_product_name: "Clever Closet"
meta_title: "Clever Closet - Smaller Closet, Bigger Impact"
meta_description: "Your actions go beyond your closet. Donations and practicing mindful shopping reduces waste and your overall carbon footprint."
meta_image: "cover2.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
