meta_product_name: "Clever Closet"
meta_title: "Clever Closet - Product Tagline"
meta_description: "Add description"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
